### ISSUE TITLE
Incompatibility with Spring Cloud

### ISSUE THREAD

**Issue by Cepr0** [candrews/log4jdbc-spring-boot-starter#13]
Any Spring Cloud dependencies lead to the crash of the application with exception:

```
IllegalArgumentException: ExistingValue must be an instance of com.zaxxer.hikari.HikariDataSource
```

Stack trace:

```
Caused by: java.lang.IllegalArgumentException: ExistingValue must be an instance of com.zaxxer.hikari.HikariDataSource
	at org.springframework.util.Assert.isTrue(Assert.java:136) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.context.properties.bind.Bindable.withExistingValue(Bindable.java:161) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBean.create(ConfigurationPropertiesBean.java:268) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBean.get(ConfigurationPropertiesBean.java:201) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesBeans.postProcessBeforeInitialization(ConfigurationPropertiesBeans.java:94) ~[spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	... 47 common frames omitted
```

If we exclude Spring Cloud dependencies from the project - it runs successfully.

Please check my [demo](https://github.com/Cepr0/sb-log4jdbc-cloud-demo).

**Comment by Cepr0** [comment]
My [workaround](https://github.com/Cepr0/sb-log4jdbc-cloud-workaround-demo)
